# Generated by Django 2.2.5 on 2019-09-10 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0016_auto_20190910_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='stats',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='stats',
        ),
        migrations.RemoveField(
            model_name='video',
            name='stats',
        ),
        migrations.DeleteModel(
            name='Stats',
        ),
    ]
