# Generated by Django 2.2.5 on 2019-09-10 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0017_auto_20190910_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='image',
            name='review',
        ),
        migrations.RemoveField(
            model_name='image',
            name='rights',
        ),
        migrations.RemoveField(
            model_name='video',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='video',
            name='review',
        ),
        migrations.RemoveField(
            model_name='video',
            name='rights',
        ),
    ]
