# Generated by Django 2.2.5 on 2019-09-10 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0018_auto_20190910_1934'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rights',
        ),
    ]
