# Generated by Django 2.2.5 on 2019-09-14 06:31

from django.db import migrations, models

def fill_filepath(apps, schema_editor):
    Media = apps.get_model('meta', 'Media')
    Image = apps.get_model('meta', 'Image')
    Video = apps.get_model('meta', 'Video')

    for image in Image.objects.all():
        if image.old_filepath:
            midpath = image.old_filepath.split('oficial')[1]
            endpath = 'source_media{}'.format(midpath)
            print(endpath, image.id)
            media = Media(filepath=endpath, old_image=image.id)
            media.save()

    for video in Video.objects.all():
        if video.old_filepath:
            midpath = video.old_filepath.split('oficial')[1]
            endpath = 'source_media{}'.format(midpath)
            print(endpath, video.id)
            media = Media(filepath=endpath, old_video=video.id)
            media.save()

class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0019_delete_rights'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filepath', models.CharField(help_text='Caminho único para arquivo original.', max_length=200, unique=True, verbose_name='arquivo original.')),
                ('old_image', models.PositiveIntegerField(blank=True, default=0, help_text='ID da imagem no antigo modelo.')),
                ('old_video', models.PositiveIntegerField(blank=True, default=0, help_text='ID do vídeo no antigo modelo.')),
            ],
        ),
        migrations.RunPython(fill_filepath, reverse_code=migrations.RunPython.noop),
    ]
