# Generated by Django 2.2.5 on 2019-09-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0021_auto_20190914_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='coverpath',
            field=models.ImageField(help_text='Imagem de amostra do arquivo processado.', unique=True, upload_to='', verbose_name='amostra do arquivo.'),
        ),
        migrations.AlterField(
            model_name='media',
            name='sitepath',
            field=models.FileField(help_text='Arquivo processado para a web.', unique=True, upload_to='', verbose_name='arquivo web.'),
        ),
    ]
