# Generated by Django 2.2.5 on 2019-09-14 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0023_auto_20190914_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='datatype',
            field=models.CharField(help_text='Tipo de mídia.', max_length=15, verbose_name='tipo de mídia'),
        ),
        migrations.AlterField(
            model_name='media',
            name='timestamp',
            field=models.DateTimeField(help_text='Data da última modificação do arquivo.', verbose_name='data de modificação'),
        ),
    ]
