# Generated by Django 2.2.5 on 2019-09-14 08:30

from django.db import migrations, models

def copy_data(apps, schema_editor):
    '''From highlight, is_public, pub_date.'''

    Media = apps.get_model('meta', 'Media')
    media = Media.objects.all()

    Image = apps.get_model('meta', 'Image')
    Video = apps.get_model('meta', 'Video')

    for m in media:
        if m.old_image:
            i = Image.objects.get(id=m.old_image)
            if i.highlight or i.cover:
                m.highlight = True
            m.is_public = i.is_public
            m.pub_date = i.pub_date
            m.save()

        elif m.old_video:
            v = Video.objects.get(id=m.old_video)
            if v.highlight or v.cover:
                m.highlight = True
            m.is_public = v.is_public
            m.pub_date = v.pub_date
            m.save()

        print(m.id, m.highlight, m.is_public, m.pub_date)

class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0024_auto_20190914_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='highlight',
            field=models.BooleanField(default=False, help_text='Imagem que merece destaque.', verbose_name='destaque'),
        ),
        migrations.AddField(
            model_name='media',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Visível para visitantes.', verbose_name='público'),
        ),
        migrations.AddField(
            model_name='media',
            name='pub_date',
            field=models.DateTimeField(help_text='Data de publicação da imagem no Cifonauta.', null=True, verbose_name='data de publicação'),
        ),
        migrations.RunPython(copy_data, reverse_code=migrations.RunPython.noop),
    ]
