# Generated by Django 2.2.5 on 2019-09-14 08:57

from django.db import migrations, models


def copy_data(apps, schema_editor):
    '''From date, geolocation, latitude, longitude.'''

    Media = apps.get_model('meta', 'Media')
    media = Media.objects.all()

    Image = apps.get_model('meta', 'Image')
    Video = apps.get_model('meta', 'Video')

    for m in media:
        if m.old_image:
            i = Image.objects.get(id=m.old_image)
            m.date = i.date
            m.geolocation = i.geolocation
            m.latitude = i.latitude
            m.longitude = i.longitude
            m.save()

        elif m.old_video:
            v = Video.objects.get(id=m.old_video)
            m.date = v.date
            m.geolocation = v.geolocation
            m.latitude = v.latitude
            m.longitude = v.longitude
            m.save()

        print(m.id, m.date, m.geolocation, m.latitude, m.longitude)


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0026_auto_20190914_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='date',
            field=models.DateTimeField(blank=True, help_text='Data de criação da imagem.', null=True, verbose_name='data'),
        ),
        migrations.AddField(
            model_name='media',
            name='geolocation',
            field=models.CharField(blank=True, default='', help_text='Geolocalização da imagem no formato decimal.', max_length=25, verbose_name='geolocalização'),
        ),
        migrations.AddField(
            model_name='media',
            name='latitude',
            field=models.CharField(blank=True, default='', help_text='Latitude onde a imagem foi criada.', max_length=25, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='media',
            name='longitude',
            field=models.CharField(blank=True, default='', help_text='Longitude onde a imagem foi criada.', max_length=25, verbose_name='longitude'),
        ),
        migrations.RunPython(copy_data, reverse_code=migrations.RunPython.noop),
    ]
