# Generated by Django 2.2.5 on 2019-09-14 09:17

from django.db import migrations, models

def copy_data(apps, schema_editor):
    '''From date, geolocation, latitude, longitude.'''

    Media = apps.get_model('meta', 'Media')
    media = Media.objects.all()

    Image = apps.get_model('meta', 'Image')
    Video = apps.get_model('meta', 'Video')

    for m in media:
        if m.old_image:
            i = Image.objects.get(id=m.old_image)
            m.title = i.title
            m.caption = i.caption
            m.save()

        elif m.old_video:
            v = Video.objects.get(id=m.old_video)
            m.title = v.title
            m.caption = v.caption
            m.save()

        print(m.id, m.title, m.caption)



class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0027_auto_20190914_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='caption',
            field=models.TextField(blank=True, default='', help_text='Legenda da imagem.', verbose_name='legenda'),
        ),
        migrations.AddField(
            model_name='media',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Título da imagem.', max_length=200, verbose_name='título'),
        ),
        migrations.RunPython(copy_data, reverse_code=migrations.RunPython.noop),
    ]
