# Generated by Django 2.2.5 on 2019-09-14 09:34

from django.db import migrations, models
import django.db.models.deletion

def copy_data(apps, schema_editor):
    '''From size, sublocation, city, state, country.'''

    Media = apps.get_model('meta', 'Media')
    media = Media.objects.all()

    Image = apps.get_model('meta', 'Image')
    Video = apps.get_model('meta', 'Video')

    for m in media:
        if m.old_image:
            i = Image.objects.get(id=m.old_image)
            m.size = i.size
            m.sublocation = i.sublocation
            m.city = i.city
            m.state = i.state
            m.country = i.country
            m.save()

        elif m.old_video:
            v = Video.objects.get(id=m.old_video)
            m.size = v.size
            m.sublocation = v.sublocation
            m.city = v.city
            m.state = v.state
            m.country = v.country
            m.save()

        if m.size and m.sublocation and m.city and m.state and m.country:
            print(m.id, m.size.name, m.sublocation.name, m.city.name, m.state.name, m.country.name)
        else:
            print(m.id)


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0028_auto_20190914_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='city',
            field=models.ForeignKey(blank=True, help_text='Cidade mostrada na imagem (ou cidade de coleta).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='meta.City', verbose_name='cidade'),
        ),
        migrations.AddField(
            model_name='media',
            name='country',
            field=models.ForeignKey(blank=True, help_text='País mostrado na imagem (ou país de coleta).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='meta.Country', verbose_name='país'),
        ),
        migrations.AddField(
            model_name='media',
            name='size',
            field=models.ForeignKey(blank=True, help_text='Classe de tamanho do organismo na imagem.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='meta.Size', verbose_name='tamanho'),
        ),
        migrations.AddField(
            model_name='media',
            name='state',
            field=models.ForeignKey(blank=True, help_text='Estado mostrado na imagem (ou estado de coleta).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='meta.State', verbose_name='estado'),
        ),
        migrations.AddField(
            model_name='media',
            name='sublocation',
            field=models.ForeignKey(blank=True, help_text='Localidade mostrada na imagem (ou local de coleta).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='meta.Sublocation', verbose_name='local'),
        ),
        migrations.RunPython(copy_data, reverse_code=migrations.RunPython.noop),
    ]
