# Generated by Django 2.2.5 on 2019-09-14 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0029_auto_20190914_0934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['id'], 'verbose_name': 'arquivo', 'verbose_name_plural': 'arquivos'},
        ),
    ]
