# Generated by Django 2.2.5 on 2019-09-14 13:25

from django.db import migrations, models
import django.db.models.deletion

def import_media(apps, schema_editor):
    '''From the Tag images and videos.'''

    Tag = apps.get_model('meta', 'Tag')
    Media = apps.get_model('meta', 'Media')
    tags = Tag.objects.all()

    for tag in tags:

        if tag.images.all():
            for image in tag.images.all():
                try:
                    media = Media.objects.get(old_image=image.id)
                    tag.media.add(media)
                except:
                    continue

        if tag.videos.all():
            for video in tag.videos.all():
                try:
                    media = Media.objects.get(old_video=video.id)
                    tag.media.add(media)
                except:
                    continue

        tag.save()

        print(tag.id, tag.name, tag.slug, tag.description, tag.media.count())


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0031_person'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'marcador', 'verbose_name_plural': 'marcadores'},
        ),
        migrations.AddField(
            model_name='tag',
            name='media',
            field=models.ManyToManyField(blank=True, help_text='Fotos associadas a este marcador.', to='meta.Media', verbose_name='fotos'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Descrição do marcador.', verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description_en',
            field=models.TextField(blank=True, default='', help_text='Descrição do marcador.', null=True, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description_pt_br',
            field=models.TextField(blank=True, default='', help_text='Descrição do marcador.', null=True, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Categoria a que este marcador pertence.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to='meta.TagCategory', verbose_name='categoria'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, default='', help_text='Slug do nome do marcador.', max_length=64, verbose_name='slug'),
        ),
        migrations.RunPython(import_media, reverse_code=migrations.RunPython.noop),
    ]
