# Generated by Django 2.2.5 on 2019-09-14 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0032_auto_20190914_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='image_count',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='position',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='video_count',
        ),
    ]
