# Generated by Django 2.2.5 on 2019-09-14 14:01

from django.db import migrations, models
import django.db.models.deletion

def import_media(apps, schema_editor):
    '''From the Tag images and videos.'''

    Taxon = apps.get_model('meta', 'Taxon')
    Media = apps.get_model('meta', 'Media')
    taxa = Taxon.objects.all()

    for taxon in taxa:

        if taxon.images.all():
            for image in taxon.images.all():
                try:
                    media = Media.objects.get(old_image=image.id)
                    taxon.media.add(media)
                except:
                    continue

        if taxon.videos.all():
            for video in taxon.videos.all():
                try:
                    media = Media.objects.get(old_video=video.id)
                    taxon.media.add(media)
                except:
                    continue

        taxon.save()

        print(taxon.id, taxon.name, taxon.slug, taxon.rank, taxon.media.count())


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0034_auto_20190914_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxon',
            name='media',
            field=models.ManyToManyField(blank=True, help_text='Fotos associadas a este táxon.', to='meta.Media', verbose_name='fotos'),
        ),
        migrations.AddField(
            model_name='taxon',
            name='timestamp',
            field=models.DateTimeField(blank=True, help_text='Data da última modificação do arquivo.', null=True, verbose_name='data de modificação'),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Táxon pai deste táxon.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='meta.Taxon', verbose_name='pai'),
        ),
        migrations.RunPython(import_media, reverse_code=migrations.RunPython.noop),
    ]
