# Generated by Django 2.2.5 on 2019-09-14 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0037_auto_20190914_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='image_count',
        ),
        migrations.RemoveField(
            model_name='size',
            name='video_count',
        ),
    ]
