# Generated by Django 2.2.5 on 2019-09-15 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0040_auto_20190915_0810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='image_count',
        ),
        migrations.RemoveField(
            model_name='state',
            name='video_count',
        ),
    ]
