# Generated by Django 2.2.5 on 2019-09-15 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0041_auto_20190915_0813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name': 'país', 'verbose_name_plural': 'país'},
        ),
        migrations.RemoveField(
            model_name='country',
            name='image_count',
        ),
        migrations.RemoveField(
            model_name='country',
            name='video_count',
        ),
    ]
