# Generated by Django 2.2.5 on 2019-09-15 08:24

from django.db import migrations, models

def import_media(apps, schema_editor):
    '''From the Reference images and videos.'''

    Reference = apps.get_model('meta', 'Reference')
    Media = apps.get_model('meta', 'Media')
    references = Reference.objects.all()

    for reference in references:

        if reference.images.all():
            for image in reference.images.all():
                try:
                    media = Media.objects.get(old_image=image.id)
                    reference.media.add(media)
                except:
                    continue

        if reference.videos.all():
            for video in reference.videos.all():
                try:
                    media = Media.objects.get(old_video=video.id)
                    reference.media.add(media)
                except:
                    continue

        reference.save()

        print(reference.id, reference.citation, reference.media.count())

class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0042_auto_20190915_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='media',
            field=models.ManyToManyField(blank=True, help_text='Fotos associadas à esta referência.', to='meta.Media', verbose_name='fotos'),
        ),
        migrations.RunPython(import_media, reverse_code=migrations.RunPython.noop),
    ]
