# Generated by Django 2.2.5 on 2019-09-15 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0043_reference_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='image_count',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='video_count',
        ),
    ]
