# Generated by Django 2.2.5 on 2019-09-15 08:41

from django.db import migrations, models

def import_media(apps, schema_editor):
    '''From the Tour images and videos.'''

    Tour = apps.get_model('meta', 'Tour')
    Media = apps.get_model('meta', 'Media')
    tours = Tour.objects.all()

    for tour in tours:

        if tour.images.all():
            for image in tour.images.all():
                try:
                    media = Media.objects.get(old_image=image.id)
                    tour.media.add(media)
                except:
                    continue

        if tour.videos.all():
            for video in tour.videos.all():
                try:
                    media = Media.objects.get(old_video=video.id)
                    tour.media.add(media)
                except:
                    continue

        tour.save()

        print(tour.id, tour.name, tour.media.count())

class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0044_auto_20190915_0833'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': ['name'], 'verbose_name': 'tour', 'verbose_name_plural': 'tours'},
        ),
        migrations.AddField(
            model_name='tour',
            name='media',
            field=models.ManyToManyField(blank=True, help_text='Arquivos associadas a este tour.', to='meta.Media', verbose_name='arquivos'),
        ),
        migrations.RunPython(import_media, reverse_code=migrations.RunPython.noop),
    ]
