# Generated by Django 2.2.5 on 2019-09-15 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0045_auto_20190915_0841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='image_count',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='video_count',
        ),
        migrations.DeleteModel(
            name='TourPosition',
        ),
    ]
