# Generated by Django 2.2.5 on 2019-09-15 13:23

from django.db import migrations, models

def copy_translations(apps, schema_editor):
    '''From previous Image and Video models.'''

    Media = apps.get_model('meta', 'Media')
    Image = apps.get_model('meta', 'Image')
    Video = apps.get_model('meta', 'Video')
    media = Media.objects.all()

    for m in media:
        if m.old_image:
            i = Image.objects.get(id=m.old_image)
            m.title_pt_br = i.title_pt_br
            m.title_en = i.title_en
            m.caption_pt_br = i.caption_pt_br
            m.caption_en = i.caption_en
            m.save()

        elif m.old_video:
            v = Video.objects.get(id=m.old_video)
            m.title_pt_br = v.title_pt_br
            m.title_en = v.title_en
            m.caption_pt_br = v.caption_pt_br
            m.caption_en = v.caption_en
            m.save()

        print(m.id, m.title_pt_br, m.title_en)
        print(m.id, m.caption_pt_br, m.caption_en)

class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0046_auto_20190915_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='caption_en',
            field=models.TextField(blank=True, default='', help_text='Legenda da imagem.', null=True, verbose_name='legenda'),
        ),
        migrations.AddField(
            model_name='media',
            name='caption_pt_br',
            field=models.TextField(blank=True, default='', help_text='Legenda da imagem.', null=True, verbose_name='legenda'),
        ),
        migrations.AddField(
            model_name='media',
            name='title_en',
            field=models.CharField(blank=True, default='', help_text='Título da imagem.', max_length=200, null=True, verbose_name='título'),
        ),
        migrations.AddField(
            model_name='media',
            name='title_pt_br',
            field=models.CharField(blank=True, default='', help_text='Título da imagem.', max_length=200, null=True, verbose_name='título'),
        ),
        migrations.RunPython(copy_translations, reverse_code=migrations.RunPython.noop),
    ]
