# Generated by Django 2.2.5 on 2019-09-29 17:04

from django.db import migrations, models

def size_class(apps, schema_editor):
    '''Convert Size to a tag.'''

    Media = apps.get_model('meta', 'Media')
    Tag = apps.get_model('meta', 'Tag')

    for entry in Media.objects.all():

        if not entry.size:
            entry.size_class = 'none'
        else:
            size_tag = Tag.objects.get(name=entry.size.name)
            entry.size_class = size_tag.slug

        entry.save()

        print(entry.id, entry.size_class)


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0049_auto_20190929_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='size_class',
            field=models.CharField(blank=True, default='none', help_text='Classe de tamanho.', max_length=10, verbose_name='tamanho'),
        ),
        migrations.RunPython(size_class, reverse_code=migrations.RunPython.noop),
    ]
