# Generated by Django 2.2.5 on 2019-09-29 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0051_auto_20190929_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='size_class',
            new_name='size',
        ),
    ]
