# Generated by Django 2.2.5 on 2019-10-06 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0052_auto_20190929_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='parent',
            new_name='category',
        ),
    ]
