# Generated by Django 2.2.5 on 2019-10-06 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0053_auto_20191006_1411'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TagCategory',
            new_name='Category',
        ),
    ]
