# Generated by Django 2.2.5 on 2019-11-04 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0054_auto_20191006_1422'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sublocation',
            new_name='Location',
        ),
        migrations.RenameField(
            model_name='media',
            old_name='sublocation',
            new_name='location',
        ),
    ]
