# Generated by Django 2.2.5 on 2019-12-01 13:47

from django.db import migrations, models

def fill_stats(apps, schema_editor):
    '''Fill in database stats.'''

    Stats = apps.get_model('meta', 'Stats')
    Media = apps.get_model('meta', 'Media')
    Tag = apps.get_model('meta', 'Tag')
    Taxon = apps.get_model('meta', 'Taxon')
    Location = apps.get_model('meta', 'Location')

    cifo = Stats(site='cifonauta')

    cifo.photos = Media.objects.filter(is_public=True, datatype='photo').count()
    cifo.videos = Media.objects.filter(is_public=True, datatype='video').count()
    cifo.tags = Tag.objects.count()
    cifo.species = Taxon.objects.filter(rank_en='Species').count()
    cifo.locations = Location.objects.count()

    cifo.save()

    print(cifo)


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0055_auto_20191104_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(help_text='Nome do site.', max_length=100, unique=True, verbose_name='nome')),
                ('photos', models.PositiveIntegerField(default=0, help_text='Número total de fotos públicas.')),
                ('videos', models.PositiveIntegerField(default=0, help_text='Número total de vídeos públicos.')),
                ('tags', models.PositiveIntegerField(default=0, help_text='Número total de marcadores.')),
                ('species', models.PositiveIntegerField(default=0, help_text='Número total de espécies.')),
                ('locations', models.PositiveIntegerField(default=0, help_text='Número total de localidades.')),
            ],
        ),
        migrations.RunPython(fill_stats, reverse_code=migrations.RunPython.noop),
    ]
