# Generated by Django 2.2.5 on 2019-12-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0056_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='site',
            field=models.CharField(help_text='Nome do sítio.', max_length=100, unique=True, verbose_name='website'),
        ),
    ]
