# Generated by Django 2.2.28 on 2023-03-03 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0058_auto_20230303_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxon',
            name='authority',
            field=models.CharField(blank=True, help_text='Autoridade do táxon.', max_length=256, verbose_name='autoridade'),
        ),
    ]
