# Generated by Django 2.2.28 on 2023-03-03 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0059_taxon_authority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxon',
            name='authority',
            field=models.CharField(blank=True, help_text='Autoridade do táxon.', max_length=256, null=True, verbose_name='autoridade'),
        ),
    ]
