# Generated by Django 2.2.28 on 2023-03-03 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0060_auto_20230303_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxon',
            name='is_valid',
            field=models.BooleanField(default=False, help_text='Status do táxon.', verbose_name='válido'),
        ),
    ]
