# Generated by Django 2.2.28 on 2023-03-06 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0062_taxon_parent_aphia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxon',
            name='parent_aphia',
        ),
    ]
