# Generated by Django 2.2.28 on 2023-03-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0063_remove_taxon_parent_aphia'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxon',
            name='status',
            field=models.CharField(blank=True, help_text='Status do táxon.', max_length=256, null=True, verbose_name='status'),
        ),
    ]
