# Generated by Django 2.2.28 on 2023-03-07 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0065_taxon_valid_taxon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxon',
            name='valid_taxon',
            field=models.ForeignKey(blank=True, help_text='Sinônimo válido deste táxon.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='synonyms', to='meta.Taxon', verbose_name='táxon válido'),
        ),
    ]
