# Generated by Django 4.2.1 on 2023-07-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('meta', '0067_auto_20230307_0126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curadoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('groups', models.ManyToManyField(blank=True, to='auth.group')),
            ],
        ),
    ]
