# Generated by Django 4.2.1 on 2023-07-29 20:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0069_media_author_media_curadoria_media_file_media_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Data de publicação da imagem no Cifonauta.', verbose_name='data de publicação'),
        ),
        migrations.AlterField(
            model_name='media',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Data da última modificação do arquivo.', verbose_name='data de modificação'),
        ),
    ]
