# Generated by Django 4.2.1 on 2023-07-31 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0070_alter_media_pub_date_alter_media_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='coverpath',
            field=models.ImageField(help_text='Imagem de amostra do arquivo processado.', upload_to='', verbose_name='amostra do arquivo.'),
        ),
        migrations.AlterField(
            model_name='media',
            name='sitepath',
            field=models.FileField(help_text='Arquivo processado para a web.', upload_to='', verbose_name='arquivo web.'),
        ),
    ]
