# Generated by Django 4.2.1 on 2023-08-07 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0075_curadoria_specialists_alter_curadoria_curators'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curadoria',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='media',
            name='curadoria',
        ),
    ]
