# Generated by Django 4.2.1 on 2023-08-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0078_alter_curadoria_curators_alter_curadoria_specialists'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='taxons',
            field=models.ManyToManyField(blank=True, related_name='taxons', to='meta.taxon', verbose_name='táxons'),
        ),
    ]
