# Generated by Django 4.2.1 on 2023-08-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0079_media_taxons'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='has_taxons',
            field=models.BooleanField(default=False, help_text='Media tem táxons.', verbose_name='tem táxons'),
        ),
    ]
