# Generated by Django 4.2.1 on 2023-08-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0081_alter_media_has_taxons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='has_taxons',
            field=models.CharField(choices=[('True', 'Sim'), ('False', 'Não')], default='False', help_text='Media tem táxons.', verbose_name='tem táxons'),
        ),
    ]
