# Generated by Django 4.2.1 on 2023-08-10 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meta', '0084_userpreregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='co_author',
            field=models.ManyToManyField(blank=True, help_text='Coautor(es) da mídia', related_name='co_author', to=settings.AUTH_USER_MODEL, verbose_name='coautor'),
        ),
        migrations.AlterField(
            model_name='media',
            name='author',
            field=models.ForeignKey(help_text='Autor da mídia.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='autor'),
        ),
    ]
