# Generated by Django 4.2.1 on 2023-08-13 17:10

from django.db import migrations, models
import meta.models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0086_remove_media_co_author_media_co_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(blank=True, default=None, null=True),
        ),
    ]
