# Generated by Django 4.2.1 on 2023-08-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0087_alter_media_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='license',
            field=models.CharField(blank=True, choices=[('cc0', 'CC0 (Domínio Público)'), ('cc_by', 'CC BY (Atribuição)'), ('cc_by_sa', 'CC BY-SA (Atribuição-CompartilhaIgual)'), ('cc_by_nd', '(Atribuição-SemDerivações)'), ('cc_by_nc', '(Atribuição-NãoComercial)'), ('cc_by_nc_sa', '(AtribuiçãoNãoComercial-CompartilhaIgual)'), ('cc_by_nc_sa', '(AtribuiçãoNãoComercial-CompartilhaIgual)'), ('cc_by_nc_nd', '(Atribuição-SemDerivações-SemDerivados)')], help_text='Tipo de licença que a mídia terá', max_length=60, verbose_name='Licença'),
        ),
    ]
