# Generated by Django 4.2.1 on 2023-08-14 15:29

from django.db import migrations, models
import meta.models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0088_media_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(default=None, null=True, upload_to=meta.models.upload_to),
        ),
        migrations.AlterField(
            model_name='media',
            name='license',
            field=models.CharField(choices=[('cc0', 'CC0 (Domínio Público)'), ('cc_by', 'CC BY (Atribuição)'), ('cc_by_sa', 'CC BY-SA (Atribuição-CompartilhaIgual)'), ('cc_by_nd', 'CC BY-ND (Atribuição-SemDerivações)'), ('cc_by_nc', 'CC BY-NC (Atribuição-NãoComercial)'), ('cc_by_nc_sa', 'CC BY-NC-SA (AtribuiçãoNãoComercial-CompartilhaIgual)'), ('cc_by_nc_nd', ' CC BY-NC-ND (Atribuição-SemDerivações-SemDerivados)')], default='cc0', help_text='Tipo de licença que a mídia terá', max_length=60, verbose_name='Licença'),
        ),
    ]
