# Generated by Django 4.2.1 on 2023-08-16 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0089_alter_media_file_alter_media_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='co_author',
            field=models.CharField(blank=True, help_text='Coautor(es) da mídia', max_length=256, verbose_name='coautor'),
        ),
    ]
