# Generated by Django 4.2.1 on 2023-08-16 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0090_alter_media_co_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='co_author',
        ),
    ]
