# Generated by Django 4.2.1 on 2023-08-16 23:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meta', '0091_remove_media_co_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='co_author',
            field=models.OneToOneField(help_text='Coautor(es) da mídia', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_author', to=settings.AUTH_USER_MODEL, verbose_name='coautor'),
        ),
    ]
