# Generated by Django 4.2.3 on 2023-08-21 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0091_media_software_media_tag_habitat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
