# Generated by Django 4.2.1 on 2023-08-16 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0092_media_co_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='co_author',
            field=models.OneToOneField(help_text='Coautor(es) da mídia', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_author', to='meta.person', verbose_name='coautor'),
        ),
    ]
