# Generated by Django 4.2.1 on 2023-08-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0093_alter_media_co_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='orcid',
            field=models.CharField(max_length=16, null=True, verbose_name='Orcid'),
        ),
    ]
