# Generated by Django 4.2.3 on 2023-08-21 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0093_media_license_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='specialist',
            field=models.ManyToManyField(blank=True, related_name='pessoas', to='meta.person', verbose_name='Especialista'),
        ),
    ]
