# Generated by Django 4.2.3 on 2023-08-21 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0094_media_specialist'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='credit',
            field=models.CharField(blank=True, help_text='Referências bibliográficas relacionadas com a imagem.', verbose_name='Referências Bibliográficas'),
        ),
    ]
