# Generated by Django 4.2.1 on 2023-08-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0094_person_orcid'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='terms',
            field=models.BooleanField(default=False, verbose_name='termos'),
        ),
    ]
