# Generated by Django 4.2.3 on 2023-08-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0095_media_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='co_author',
            field=models.CharField(blank=True, help_text='Coautor(es) da mídia separados por ";"', max_length=256, verbose_name='coautor'),
        ),
    ]
