# Generated by Django 4.2.1 on 2023-08-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0096_alter_media_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='terms',
            field=models.BooleanField(default=False, verbose_name='termos'),
        ),
    ]
