# Generated by Django 4.2.3 on 2023-08-30 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0096_alter_media_co_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='license_year',
        ),
    ]
