# Generated by Django 4.2.1 on 2023-08-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0098_person_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='co_author',
        ),
        migrations.AddField(
            model_name='media',
            name='co_author',
            field=models.ManyToManyField(help_text='Coautor(es) da mídia', null=True, related_name='co_author', to='meta.person', verbose_name='coautor'),
        ),
    ]
