# Generated by Django 4.2.1 on 2023-08-29 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0100_alter_media_co_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPreRegistration',
        ),
    ]
