# Generated by Django 4.2.1 on 2023-08-31 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0101_delete_userpreregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelTeste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teste', models.FileField(default=None, null=True, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='media',
            name='taxons',
            field=models.ManyToManyField(blank=True, help_text='Táxons pertencentes à mídia.', related_name='taxons', to='meta.taxon', verbose_name='táxons'),
        ),
    ]
