# Generated by Django 4.2.1 on 2023-08-31 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0102_modelteste_alter_media_taxons'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelteste',
            name='testenome',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome'),
        ),
    ]
