# Generated by Django 4.2.1 on 2023-08-31 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0103_modelteste_testenome'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelTeste',
        ),
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
    ]
