# Generated by Django 4.2.1 on 2023-09-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0106_alter_media_coverpath_alter_media_sitepath'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='idlattes',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='IDLattes'),
        ),
    ]
