# Generated by Django 4.2.1 on 2023-09-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0107_person_idlattes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='person',
            name='orcid',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Orcid'),
        ),
    ]
