# Generated by Django 4.2.1 on 2023-09-05 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0097_remove_media_license_year'),
        ('meta', '0109_alter_media_city_alter_media_country_and_more'),
    ]

    operations = [
    ]
