# Generated by Django 4.2.1 on 2023-09-12 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0111_remove_media_co_author_alter_media_terms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModifiedMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', help_text='Título da imagem.', max_length=200, verbose_name='título')),
                ('media', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='modified_media', to='meta.media', verbose_name='mídia modificada')),
            ],
        ),
    ]
