# Generated by Django 4.2.1 on 2023-09-12 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0112_modifiedmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='modifiedmedia',
            name='city',
            field=models.ForeignKey(help_text='Cidade mostrada na imagem (ou cidade de coleta).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='meta.city', verbose_name='cidade'),
        ),
        migrations.AddField(
            model_name='modifiedmedia',
            name='co_author',
            field=models.ManyToManyField(blank=True, help_text='Coautor(es) da mídia', related_name='modified_co_author', to='meta.person', verbose_name='coautor'),
        ),
        migrations.AddField(
            model_name='modifiedmedia',
            name='country',
            field=models.ForeignKey(help_text='País mostrado na imagem (ou país de coleta).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='meta.country', verbose_name='país'),
        ),
        migrations.AddField(
            model_name='modifiedmedia',
            name='date',
            field=models.DateTimeField(help_text='Data de criação da imagem.', null=True, verbose_name='data'),
        ),
        migrations.AddField(
            model_name='modifiedmedia',
            name='geolocation',
            field=models.CharField(blank=True, default='', help_text='Geolocalização da imagem no formato decimal.', max_length=25, verbose_name='geolocalização'),
        ),
        migrations.AddField(
            model_name='modifiedmedia',
            name='has_taxons',
            field=models.CharField(choices=[('True', 'Sim'), ('False', 'Não')], default='False', help_text='Mídia tem táxons.', verbose_name='tem táxons'),
        ),
        migrations.AddField(
            model_name='modifiedmedia',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Localidade mostrada na imagem (ou local de coleta).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='meta.location', verbose_name='local'),
        ),
        migrations.AddField(
            model_name='modifiedmedia',
            name='state',
            field=models.ForeignKey(help_text='Estado mostrado na imagem (ou estado de coleta).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='meta.state', verbose_name='estado'),
        ),
        migrations.AddField(
            model_name='modifiedmedia',
            name='taxons',
            field=models.ManyToManyField(blank=True, help_text='Táxons pertencentes à mídia.', related_name='modified_taxons', to='meta.taxon', verbose_name='táxons'),
        ),
    ]
