# Generated by Django 4.2.3 on 2023-09-13 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0113_modifiedmedia_city_modifiedmedia_co_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='metadata_error',
            field=models.BooleanField(default=False, verbose_name='Erro nos metadados'),
        ),
    ]
