# Generated by Django 4.2.1 on 2023-09-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0115_loadedmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='modifiedmedia',
            name='caption',
            field=models.TextField(blank=True, default='', help_text='Legenda da imagem.', verbose_name='legenda'),
        ),
    ]
