# Generated by Django 4.2.3 on 2023-09-29 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0116_modifiedmedia_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='tag_life_stage_test',
            field=models.ForeignKey(limit_choices_to={'category': 'Estágio de Vida'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='life_stage_test', to='meta.tag', verbose_name='Estágio de Vida'),
        ),
    ]
