# Generated by Django 4.2.3 on 2023-10-05 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0122_alter_media_tag_habitat_test_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='tag_habitat_test',
            new_name='habitat',
        ),
        migrations.RenameField(
            model_name='media',
            old_name='tag_life_stage_test',
            new_name='life_stage',
        ),
        migrations.RenameField(
            model_name='media',
            old_name='tag_life_style_test',
            new_name='life_style',
        ),
        migrations.RenameField(
            model_name='media',
            old_name='tag_microscopy_test',
            new_name='microscopy',
        ),
        migrations.RenameField(
            model_name='media',
            old_name='tag_photographic_technique_test',
            new_name='photographic_technique',
        ),
        migrations.RenameField(
            model_name='media',
            old_name='tag_several_test',
            new_name='several',
        ),
        migrations.RemoveField(
            model_name='media',
            name='tag_habitat',
        ),
        migrations.RemoveField(
            model_name='media',
            name='tag_life_stage',
        ),
        migrations.RemoveField(
            model_name='media',
            name='tag_lifestyle',
        ),
        migrations.RemoveField(
            model_name='media',
            name='tag_microscopy',
        ),
        migrations.RemoveField(
            model_name='media',
            name='tag_photographic_technique',
        ),
        migrations.RemoveField(
            model_name='media',
            name='tag_several',
        ),
    ]
