# Generated by Django 4.2.1 on 2023-10-09 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0123_rename_tag_habitat_test_media_habitat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='country',
            field=models.ForeignKey(blank=True, help_text='Pais na qual o estado pertence.', null=True, on_delete=django.db.models.deletion.CASCADE, to='meta.country', verbose_name='país'),
        ),
    ]
