# Generated by Django 4.2.1 on 2023-10-09 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0124_state_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(blank=True, help_text='Estado na qual a cidade pertence.', null=True, on_delete=django.db.models.deletion.CASCADE, to='meta.state', verbose_name='estado'),
        ),
    ]
