# Generated by Django 4.2.1 on 2023-10-09 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0125_city_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='city',
            field=models.ForeignKey(blank=True, help_text='Cidade mostrada na imagem (ou cidade de coleta).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='meta.city', verbose_name='cidade'),
        ),
        migrations.AlterField(
            model_name='media',
            name='state',
            field=models.ForeignKey(blank=True, help_text='Estado mostrado na imagem (ou estado de coleta).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='meta.state', verbose_name='estado'),
        ),
    ]
