# Generated by Django 4.2.1 on 2023-10-17 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0126_alter_media_city_alter_media_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='has_taxons',
        ),
        migrations.RemoveField(
            model_name='media',
            name='taxons',
        ),
    ]
