# Generated by Django 4.2.1 on 2023-10-17 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0127_remove_media_has_taxons_remove_media_taxons'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loadedmedia',
            options={'verbose_name': 'mídia carregada', 'verbose_name_plural': 'mídias carregadas'},
        ),
        migrations.AlterModelOptions(
            name='modifiedmedia',
            options={'verbose_name': 'mídia modificada', 'verbose_name_plural': 'mídias modificadas'},
        ),
        migrations.RemoveField(
            model_name='modifiedmedia',
            name='has_taxons',
        ),
    ]
