# Generated by Django 4.2.1 on 2023-10-26 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meta', '0129_tour_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='creator',
            field=models.ForeignKey(help_text='Usuário criador do tour.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='criador'),
        ),
    ]
