# Generated by Django 4.2.3 on 2023-10-29 13:53

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0130_alter_tour_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(help_text='Campo que guarda o vetor de busca.', null=True, verbose_name='vetor de busca'),
        ),
    ]
