# Generated by Django 4.2.3 on 2023-11-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0132_media_meta_media_search__fc903c_gin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
