# Generated by Django 4.2.3 on 2023-11-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0135_media_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='authors',
            field=models.ManyToManyField(blank=True, help_text='Coautor(es) da mídia', related_name='authors', to='meta.person', verbose_name='autors'),
        ),
    ]
