# Generated by Django 4.2.3 on 2023-11-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0136_media_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='authors',
            field=models.ManyToManyField(blank=True, help_text='Autores associates a este arquivo.', related_name='authors', to='meta.person', verbose_name='autores do arquivo'),
        ),
    ]
