# Generated by Django 4.2.3 on 2023-11-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0138_alter_media_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='specialists',
            field=models.ManyToManyField(blank=True, help_text='Especialistas associados a este arquivo.', related_name='specialists', to='meta.person', verbose_name='especialistas associados'),
        ),
        migrations.AlterField(
            model_name='media',
            name='authors',
            field=models.ManyToManyField(blank=True, help_text='Autores associados a este arquivo.', related_name='authors', to='meta.person', verbose_name='autores do arquivo'),
        ),
    ]
