# Generated by Django 4.2.3 on 2023-11-01 16:17

from django.db import migrations


def assign_media_authors_and_specialists(apps, schema_editor):
    '''Migrate Media data from person_set to authors and specialists.'''
    Media = apps.get_model('meta', 'Media')

    for media in Media.objects.all():

        # Get all persons of this media who are authors
        authors = [person for person in media.person_set.all() if person.is_author]

        # Get all persons of this media who are specialists
        specialists = [person for person in media.person_set.all() if not person.is_author]
        # Set the new authors field with new authors list
        media.authors.set(authors)

        # Set the new specialists field with new specialists list
        media.specialists.set(specialists)

        # Save 
        media.save()


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0139_media_specialists_alter_media_authors'),
    ]

    operations = [
            migrations.RunPython(assign_media_authors_and_specialists),
    ]
