# Generated by Django 4.2.3 on 2023-11-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0141_alter_media_authors_alter_media_specialists_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Marcadores associados a este arquivo.', null=True, related_name='tag_media', to='meta.tag', verbose_name='marcadores do arquivo'),
        ),
    ]
