# Generated by Django 4.2.3 on 2023-11-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0142_media_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Marcadores associados a este arquivo.', related_name='tag_media', to='meta.tag', verbose_name='marcadores do arquivo'),
        ),
    ]
