# Generated by Django 4.2.3 on 2023-11-01 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meta', '0143_alter_media_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='authors',
            field=models.ManyToManyField(blank=True, help_text='Autores associados a este arquivo.', related_name='media_as_author', to='meta.person', verbose_name='autores do arquivo'),
        ),
        migrations.AlterField(
            model_name='media',
            name='specialists',
            field=models.ManyToManyField(blank=True, help_text='Especialistas associados a este arquivo.', related_name='media_as_specialist', to='meta.person', verbose_name='especialistas associados'),
        ),
        migrations.AlterField(
            model_name='media',
            name='user',
            field=models.ForeignKey(help_text='Usuário que fez o upload do arquivo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media', to=settings.AUTH_USER_MODEL, verbose_name='usuário do arquivo'),
        ),
    ]
