# Generated by Django 4.2.3 on 2023-11-01 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0144_alter_media_authors_alter_media_specialists_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='taxa',
            field=models.ManyToManyField(blank=True, help_text='Grupos taxonômicos associados com esta mídia.', related_name='media_files', to='meta.taxon', verbose_name='táxons da mídia'),
        ),
        migrations.AlterField(
            model_name='media',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Marcadores associados com esta mídia.', related_name='media_files', to='meta.tag', verbose_name='marcadores da mídia'),
        ),
    ]
