# Generated by Django 4.2.3 on 2023-11-01 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0145_media_taxa_alter_media_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='references',
            field=models.ManyToManyField(blank=True, help_text='Referências bibliográficas associadas com esta mídia.', related_name='media_files', to='meta.reference', verbose_name='referências da mídia'),
        ),
    ]
