# Generated by Django 4.2.3 on 2023-11-01 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0146_media_references'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='city',
            field=models.ForeignKey(blank=True, help_text='Cidade mostrada na imagem ou cidade de coleta.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='meta.city', verbose_name='cidade'),
        ),
        migrations.AlterField(
            model_name='media',
            name='coverpath',
            field=models.ImageField(default=None, help_text='Imagem de capa para o arquivo processado.', upload_to='', verbose_name='imagem de capa'),
        ),
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(default=None, help_text='Arquivo carregado pelo usuário.', null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='media',
            name='filepath',
            field=models.CharField(help_text='Caminho único para o arquivo original.', max_length=200, verbose_name='arquivo original'),
        ),
        migrations.AlterField(
            model_name='media',
            name='license',
            field=models.CharField(choices=[('cc0', 'CC0 (Domínio Público)'), ('cc_by', 'CC BY (Atribuição)'), ('cc_by_sa', 'CC BY-SA (Atribuição-CompartilhaIgual)'), ('cc_by_nd', 'CC BY-ND (Atribuição-SemDerivações)'), ('cc_by_nc', 'CC BY-NC (Atribuição-NãoComercial)'), ('cc_by_nc_sa', 'CC BY-NC-SA (AtribuiçãoNãoComercial-CompartilhaIgual)'), ('cc_by_nc_nd', 'CC BY-NC-ND (Atribuição-SemDerivações-SemDerivados)')], default='cc0', help_text='Tipo de licença da mídia.', max_length=60, verbose_name='Licença'),
        ),
        migrations.AlterField(
            model_name='media',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Localidade mostrada na imagem ou local de coleta.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='meta.location', verbose_name='local'),
        ),
        migrations.AlterField(
            model_name='media',
            name='metadata_error',
            field=models.BooleanField(default=False, help_text='Flag indicando problema nos metadados.', verbose_name='Erro nos metadados'),
        ),
        migrations.AlterField(
            model_name='media',
            name='sitepath',
            field=models.FileField(default=None, help_text='Arquivo processado para a web.', upload_to='', verbose_name='arquivo web'),
        ),
        migrations.AlterField(
            model_name='media',
            name='state',
            field=models.ForeignKey(blank=True, help_text='Estado mostrado na imagem ou estado de coleta.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='meta.state', verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='media',
            name='terms',
            field=models.BooleanField(default=False, help_text='Flag indicando que termos foram aceitos.', verbose_name='termos'),
        ),
    ]
