# Generated by Django 4.2.3 on 2023-11-01 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0149_remove_media_credit_remove_media_software'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='specialist',
        ),
    ]
