# Generated by Django 4.2.3 on 2023-11-01 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0150_remove_media_specialist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='co_author',
        ),
    ]
