# Generated by Django 4.2.3 on 2023-11-01 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0151_remove_media_co_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='author',
        ),
    ]
