# Generated by Django 4.2.3 on 2023-11-02 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0152_remove_media_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='media',
        ),
    ]
