# Generated by Django 4.2.3 on 2023-11-02 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0153_remove_person_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='is_author',
        ),
    ]
