# Generated by Django 4.2.3 on 2023-11-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0156_remove_tag_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Marcadores associados com esta mídia.', related_name='media', to='meta.tag', verbose_name='marcadores da mídia'),
        ),
    ]
