# Generated by Django 4.2.3 on 2023-11-02 16:58

from django.db import migrations


def migrate_taxon_data(apps, schema_editor):
    '''Migrate Media data from taxon_set to taxa.'''

    Media = apps.get_model('meta', 'Media')

    for media in Media.objects.all():

        media.taxa.set(media.taxon_set.all())

        media.save()


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0157_alter_media_tags'),
    ]

    operations = [
            migrations.RunPython(migrate_taxon_data),
    ]
