# Generated by Django 4.2.3 on 2023-11-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0158_auto_20231102_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxon',
            name='media',
        ),
        migrations.AlterField(
            model_name='media',
            name='taxa',
            field=models.ManyToManyField(blank=True, help_text='Grupos taxonômicos associados com esta mídia.', related_name='media', to='meta.taxon', verbose_name='táxons da mídia'),
        ),
    ]
