# Generated by Django 4.2.3 on 2023-11-02 19:06

from django.db import migrations


def migrate_reference_data(apps, schema_editor):
    '''Migrate Media data from reference_set to references.'''

    Media = apps.get_model('meta', 'Media')

    for media in Media.objects.all():

        media.references.set(media.reference_set.all())

        media.save()


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0159_remove_taxon_media_alter_media_taxa'),
    ]

    operations = [
            migrations.RunPython(migrate_reference_data),
    ]
