# Generated by Django 4.2.3 on 2023-11-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0160_auto_20231102_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='media',
        ),
        migrations.AlterField(
            model_name='media',
            name='references',
            field=models.ManyToManyField(blank=True, help_text='Referências bibliográficas associadas com esta mídia.', related_name='media', to='meta.reference', verbose_name='referências da mídia'),
        ),
    ]
