# Generated by Django 4.2.1 on 2023-11-03 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meta', '0161_remove_reference_media_alter_media_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='modifiedmedia',
            name='user',
            field=models.ForeignKey(help_text='Usuário que fez o upload do arquivo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_media', to=settings.AUTH_USER_MODEL, verbose_name='usuário do arquivo'),
        ),
    ]
