# Generated by Django 4.2.1 on 2023-11-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0163_remove_modifiedmedia_co_author_modifiedmedia_authors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modifiedmedia',
            name='taxons',
        ),
        migrations.AddField(
            model_name='modifiedmedia',
            name='taxa',
            field=models.ManyToManyField(blank=True, help_text='Táxons pertencentes à mídia.', related_name='modified_media_taxons', to='meta.taxon', verbose_name='táxons'),
        ),
    ]
