# Generated by Django 4.2.1 on 2023-11-06 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meta', '0164_remove_modifiedmedia_taxons_modifiedmedia_taxa'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='user_cifonauta',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário relacionado'),
        ),
    ]
