# Generated by Django 4.2.7 on 2023-11-08 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0164_remove_modifiedmedia_taxons_modifiedmedia_taxa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='size',
        ),
    ]
