# Generated by Django 4.2.1 on 2023-11-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0166_modifiedmedia_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='status',
            field=models.CharField(blank=True, choices=[('loaded', 'Carregada'), ('not_edited', 'Não Editado'), ('to_review', 'Para Revisão'), ('published', 'Publicado')], default='loaded', help_text='Status da mídia.', max_length=13, verbose_name='status'),
        ),
    ]
