# Generated by Django 4.2.1 on 2023-11-10 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0167_alter_media_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoadedMedia',
        ),
    ]
