# Generated by Django 4.2.7 on 2023-11-12 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0165_remove_media_size'),
        ('meta', '0168_delete_loadedmedia'),
    ]

    operations = [
    ]
