# Generated by Django 4.2.7 on 2023-11-12 12:55

from django.db import migrations, models
import meta.models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0169_merge_0165_remove_media_size_0168_delete_loadedmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='coverpath',
            field=models.ImageField(default=None, help_text='Imagem de capa para o arquivo processado.', upload_to=meta.models.save_cover, verbose_name='imagem de capa'),
        ),
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(default=None, help_text='Arquivo carregado pelo usuário.', null=True, upload_to=meta.models.save_file),
        ),
        migrations.AlterField(
            model_name='media',
            name='sitepath',
            field=models.FileField(default=None, help_text='Arquivo processado para a web.', upload_to=meta.models.save_cover, verbose_name='arquivo web'),
        ),
    ]
