# Generated by Django 4.2.1 on 2023-11-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0170_alter_media_coverpath_alter_media_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='curators',
            field=models.ManyToManyField(blank=True, help_text='Curadores associados a este arquivo.', related_name='media_as_curator', to='meta.person', verbose_name='curadores do arquivo'),
        ),
    ]
