# Generated by Django 4.2.7 on 2023-11-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0171_media_curators'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='date_created',
            field=models.DateTimeField(blank=True, help_text='Data de criação do arquivo.', null=True, verbose_name='data de criação'),
        ),
    ]
