# Generated by Django 4.2.7 on 2023-11-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0172_media_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='date_published',
            field=models.DateTimeField(blank=True, help_text='Data da publicação do arquivo.', null=True, verbose_name='data de publicação'),
        ),
    ]
