# Generated by Django 4.2.7 on 2023-11-19 10:48

from django.db import migrations


def migrate_creation_and_publication_dates(apps, schema_editor):
    '''Migrate date and pub_date to new date fields.'''

    Media = apps.get_model('meta', 'Media')

    for media in Media.objects.all():

        media.date_created = media.date
        media.date_published = media.pub_date

        media.save()


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0173_media_date_published'),
    ]

    operations = [
            migrations.RunPython(migrate_creation_and_publication_dates),
    ]
