# Generated by Django 4.2.7 on 2023-11-19 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0175_auto_20231119_0818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='date',
        ),
        migrations.RemoveField(
            model_name='media',
            name='pub_date',
        ),
    ]
