# Generated by Django 4.2.7 on 2023-11-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0176_remove_media_date_remove_media_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='date_modified',
            field=models.DateTimeField(blank=True, help_text='Data da última modificação do arquivo.', null=True, verbose_name='data de modificação'),
        ),
        migrations.AddField(
            model_name='media',
            name='date_uploaded',
            field=models.DateTimeField(blank=True, help_text='Data do upload do arquivo.', null=True, verbose_name='data do upload'),
        ),
    ]
