# Generated by Django 4.2.7 on 2023-11-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0178_auto_20231119_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, help_text='Data da última modificação do arquivo.', null=True, verbose_name='data de modificação'),
        ),
        migrations.AlterField(
            model_name='media',
            name='date_uploaded',
            field=models.DateTimeField(auto_now_add=True, help_text='Data do upload do arquivo.', null=True, verbose_name='data do upload'),
        ),
    ]
