# Generated by Django 4.2.7 on 2023-11-19 19:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0180_remove_media_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, help_text='Identificador único universal do arquivo.', verbose_name='identificador do arquivo'),
        ),
    ]
