# Generated by Django 4.2.7 on 2023-11-19 20:03

from django.db import migrations
import re
import uuid

def assign_and_generate_uuids(apps, schema_editor):
    '''Generate unique UUIDs and re-use pre-existing ones.'''

    Media = apps.get_model('meta', 'Media')

    uuid_regex = r'([a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12})'

    for media in Media.objects.all():

        if media.file:
            uuid_match = re.search(uuid_regex, media.file.name)
            if uuid_match:
                media.uuid = uuid_match.group(1)
            else:
                media.uuid = uuid.uuid4()
        else:
            media.uuid = uuid.uuid4()

        media.save()


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0181_media_uuid'),
    ]

    operations = [
            migrations.RunPython(assign_and_generate_uuids),
    ]
