# Generated by Django 4.2.7 on 2023-11-19 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0184_alter_media_filepath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='country',
            field=models.ForeignKey(blank=True, help_text='País mostrado na imagem (ou país de coleta).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='meta.country', verbose_name='país'),
        ),
    ]
