# Generated by Django 4.2.7 on 2023-11-20 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0186_alter_media_datatype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='datatype',
            field=models.CharField(choices=[('photo', 'photo'), ('video', 'video')], help_text='Foto ou vídeo.', max_length=15, verbose_name='tipo de mídia'),
        ),
    ]
