# Generated by Django 4.2.7 on 2023-11-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0189_remove_modifiedmedia_date_modifiedmedia_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('micro', '<0,1 mm'), ('tiny', '0,1–1,0 mm'), ('visible', '1,0–10 mm'), ('large', '10–100 mm'), ('huge', '>100 mm')], help_text='Nome da classe de tamanho.', max_length=12, unique=True, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, help_text='Slug do nome da classe de tamanho.', max_length=12, verbose_name='slug')),
                ('description', models.TextField(blank=True, help_text='Descrição da classe de tamanho.', verbose_name='descrição')),
            ],
            options={
                'verbose_name': 'escala',
                'verbose_name_plural': 'escalas',
            },
        ),
    ]
