# Generated by Django 4.2.7 on 2023-11-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0190_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='scale',
            name='description_en',
            field=models.TextField(blank=True, help_text='Descrição da classe de tamanho.', null=True, verbose_name='descrição'),
        ),
        migrations.AddField(
            model_name='scale',
            name='description_pt_br',
            field=models.TextField(blank=True, help_text='Descrição da classe de tamanho.', null=True, verbose_name='descrição'),
        ),
        migrations.AddField(
            model_name='scale',
            name='name_en',
            field=models.CharField(choices=[('micro', '<0,1 mm'), ('tiny', '0,1–1,0 mm'), ('visible', '1,0–10 mm'), ('large', '10–100 mm'), ('huge', '>100 mm')], help_text='Nome da classe de tamanho.', max_length=12, null=True, unique=True, verbose_name='nome'),
        ),
        migrations.AddField(
            model_name='scale',
            name='name_pt_br',
            field=models.CharField(choices=[('micro', '<0,1 mm'), ('tiny', '0,1–1,0 mm'), ('visible', '1,0–10 mm'), ('large', '10–100 mm'), ('huge', '>100 mm')], help_text='Nome da classe de tamanho.', max_length=12, null=True, unique=True, verbose_name='nome'),
        ),
    ]
