# Generated by Django 4.2.7 on 2023-11-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0191_scale_description_en_scale_description_pt_br_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='scale',
            field=models.CharField(blank=True, choices=[('micro', '<0,1 mm'), ('tiny', '0,1–1,0 mm'), ('visible', '1,0–10 mm'), ('large', '10–100 mm'), ('huge', '>100 mm')], help_text='Classes de escala.', max_length=12, verbose_name='escala da imagem'),
        ),
    ]
