# Generated by Django 4.2.7 on 2023-11-26 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0193_auto_20231126_1709'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scale',
        ),
    ]
