# Generated by Django 4.2.7 on 2023-11-26 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0194_delete_scale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['category', 'name'], 'verbose_name': 'marcador', 'verbose_name_plural': 'marcadores'},
        ),
    ]
