# Generated by Django 4.2.1 on 2023-12-04 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0196_alter_media_geolocation_alter_media_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modifiedmedia',
            name='city',
            field=models.ForeignKey(blank=True, help_text='Cidade mostrada na imagem (ou cidade de coleta).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='meta.city', verbose_name='cidade'),
        ),
        migrations.AlterField(
            model_name='modifiedmedia',
            name='country',
            field=models.ForeignKey(blank=True, help_text='País mostrado na imagem (ou país de coleta).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='meta.country', verbose_name='país'),
        ),
        migrations.AlterField(
            model_name='modifiedmedia',
            name='state',
            field=models.ForeignKey(blank=True, help_text='Estado mostrado na imagem (ou estado de coleta).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='meta.state', verbose_name='estado'),
        ),
    ]
