# Generated by Django 4.2.1 on 2023-12-12 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0199_alter_modifiedmedia2_options_delete_modifiedmedia'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModifiedMedia2',
            new_name='ModifiedMedia',
        ),
    ]
