# Generated by Django 4.2.1 on 2023-12-12 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0201_alter_modifiedmedia_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modifiedmedia',
            name='altered_by_author',
            field=models.BooleanField(default=True, help_text='Flag indicando que quem fez a alteração na mídia.', verbose_name='termos'),
        ),
        migrations.AlterField(
            model_name='modifiedmedia',
            name='media',
            field=models.ForeignKey(help_text='Mídia original com metadados antes das modificações.', on_delete=django.db.models.deletion.CASCADE, related_name='modified_media', to='meta.media', verbose_name='mídia original'),
        ),
    ]
