# Generated by Django 4.2.1 on 2023-12-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0202_modifiedmedia_altered_by_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modifiedmedia',
            name='altered_by_author',
            field=models.BooleanField(default=True, help_text='Flag indicando quem fez a alteração na mídia.', verbose_name='alterada pelo autor'),
        ),
    ]
