# Generated by Django 4.2.1 on 2023-12-13 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0203_alter_modifiedmedia_altered_by_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='modifiedmedia',
            name='specialist_person',
            field=models.OneToOneField(blank=True, help_text='Especialista que realizou alterações na mídia publicada', null=True, on_delete=django.db.models.deletion.CASCADE, to='meta.person', verbose_name='Especialista da mídia modificada'),
        ),
    ]
