# Generated by Django 4.2.7 on 2023-12-23 13:42

from django.db import migrations, models
import meta.models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0206_alter_media_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(default=None, help_text='Arquivo carregado pelo usuário.', null=True, upload_to=meta.models.user_upload_directory),
        ),
    ]
