# Generated by Django 4.2.7 on 2024-01-05 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0206_alter_media_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='modifiedmedia',
            name='modification_person',
            field=models.ForeignKey(help_text='Pessoa que realizou alterações na mídia publicada', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_medias', to='meta.person', verbose_name='Pessoa da mídia modificada'),
        ),
    ]
