# Generated by Django 4.2.7 on 2024-01-05 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0207_modifiedmedia_modification_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modifiedmedia',
            name='specialist_person',
        ),
    ]
