# Generated by Django 4.2.7 on 2023-12-23 16:26

from django.db import migrations, models
import meta.models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0207_alter_media_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='file_large',
            field=models.FileField(default=None, help_text='Arquivo processado em tamanho grande.', null=True, upload_to=meta.models.user_upload_directory),
        ),
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(default=None, help_text='Arquivo original carregado pelo usuário.', null=True, upload_to=meta.models.user_upload_directory),
        ),
    ]
