# Generated by Django 4.2.7 on 2023-12-23 23:08

from django.db import migrations
from django.conf import settings
from media_utils import resize_image


def create_resized_image(model, size):
    '''Resize image files to different pre-defined dimensions.

    Options: large, medium, small, cover.

    See MEDIA_DEFAULTS for details.
    '''
    # Delete file from resized field
    field = getattr(model, f'file_{size}')
    field.delete()

    # Save original file to resized field using new name
    field.save(content=model.file, name=f'{model.uuid}_{size}.jpg')

    # Get format, dimension, and quality for convenience
    format = settings.MEDIA_DEFAULTS['photo'][size]['format']
    dimension = settings.MEDIA_DEFAULTS['photo'][size]['dimension']
    quality = settings.MEDIA_DEFAULTS['photo'][size]['quality']

    # Resize image
    resized = resize_image(field.path, format, dimension, quality)


def regenerate_resized_image_fields(apps, schema_editor):
    '''Run command to create files and populate image fields.'''

    Media = apps.get_model('meta', 'Media')

    for m in Media.objects.all():
        if m.file:
            create_resized_image(m, 'large')
            create_resized_image(m, 'medium')
            create_resized_image(m, 'small')
            create_resized_image(m, 'cover')


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0209_media_file_cover_media_file_medium_media_file_small_and_more'),
    ]

    operations = [
            migrations.RunPython(regenerate_resized_image_fields),
    ]
