# Generated by Django 4.2.7 on 2024-01-19 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0209_reference_doi_reference_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='metadata',
        ),
    ]
