# Generated by Django 4.2.7 on 2023-12-23 23:08

from django.db import migrations
from django.conf import settings
from media_utils import resize_image


def create_resized_files(model, size):
    '''Resize media files to a pre-defined dimension.

    Options: large, medium, small, cover.

    See MEDIA_DEFAULTS for details.
    '''
    print(model, size)
    print(settings.MEDIA_DEFAULTS)

    # Delete file from resized field
    field = getattr(model, f'file_{size}')
    field.delete()

    # Get dimension and quality values
    dimension = settings.MEDIA_DEFAULTS[model.datatype][size]['dimension']
    quality = settings.MEDIA_DEFAULTS[model.datatype][size]['quality']
    extension = settings.MEDIA_DEFAULTS[model.datatype]['extension']

    # Force photo extension for video cover image
    if size == 'cover':
        extension = settings.MEDIA_DEFAULTS['photo']['extension']

    # Save original file to resized field using new name
    field.save(content=model.file, name=f'{model.uuid}_{size}.{extension}')

    # Resize media
    if model.datatype == 'photo':
        resized = resize_image(field.path, dimension, quality)
    elif model.datatype == 'video':
        if size == 'cover':
            resized = extract_video_cover(model.file.path, dimension,
                                          field.path)
        else:
            resized = resize_video(model.file.path, dimension,
                                   quality, field.path)

    # Return True/False for convenience
    return resized


def regenerate_resized_image_fields(apps, schema_editor):
    '''Run command to create files and populate image fields.'''

    Media = apps.get_model('meta', 'Media')

    for m in Media.objects.all():
        if m.file:
            create_resized_files(m, 'cover')
            create_resized_files(m, 'large')
            create_resized_files(m, 'medium')
            create_resized_files(m, 'small')


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0209_media_file_cover_media_file_medium_media_file_small_and_more'),
    ]

    operations = [
            migrations.RunPython(regenerate_resized_image_fields),
    ]
