# Generated by Django 4.2.7 on 2024-01-06 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0210_auto_20231223_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='coverpath',
            field=models.ImageField(default=None, help_text='Imagem de capa para o arquivo processado.', upload_to='', verbose_name='imagem de capa'),
        ),
        migrations.AlterField(
            model_name='media',
            name='sitepath',
            field=models.FileField(default=None, help_text='Arquivo processado para a web.', upload_to='', verbose_name='arquivo web'),
        ),
    ]
