# Generated by Django 4.2.7 on 2024-01-20 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0209_reference_doi_reference_metadata'),
        ('meta', '0211_alter_media_coverpath_alter_media_sitepath'),
    ]

    operations = [
    ]
