# Generated by Django 4.2.7 on 2024-01-22 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0211_alter_person_name'),
        ('meta', '0213_auto_20240120_1703'),
    ]

    operations = [
    ]
