# Generated by Django 4.2.7 on 2024-02-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0214_merge_0211_alter_person_name_0213_auto_20240120_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='acknowledgments',
            field=models.TextField(blank=True, default='', help_text='Agradecimentos da imagem.', verbose_name='agradecimentos'),
        ),
    ]
