# Generated by Django 4.2.10 on 2024-02-17 10:41

from django.db import migrations


def remove_size_tags_and_category(apps, schema_editor):
    '''Delete tags from the category size and the category itself.'''

    Tag = apps.get_model('meta', 'Tag')
    Category = apps.get_model('meta', 'Category')

    # Delete tags
    tags = Tag.objects.filter(category__name_en='Size')
    for obj in tags:
        obj.delete()

    # Delete category
    category = Category.objects.filter(name_en='Size')
    category.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0216_media_acknowledgments_en_media_acknowledgments_pt_br'),
    ]

    operations = [
            migrations.RunPython(remove_size_tags_and_category),
    ]
