# Generated by Django 4.2.11 on 2024-04-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0219_alter_location_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(help_text='Nome do estado.', max_length=64, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='state',
            name='name_en',
            field=models.CharField(help_text='Nome do estado.', max_length=64, null=True, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='state',
            name='name_pt_br',
            field=models.CharField(help_text='Nome do estado.', max_length=64, null=True, verbose_name='nome'),
        ),
    ]
