# Generated by Django 4.2.11 on 2024-04-07 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0220_alter_state_name_alter_state_name_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(help_text='Nome do país.', max_length=64, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name_en',
            field=models.CharField(help_text='Nome do país.', max_length=64, null=True, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name_pt_br',
            field=models.CharField(help_text='Nome do país.', max_length=64, null=True, verbose_name='nome'),
        ),
    ]
