# Generated by Django 4.2.11 on 2024-04-30 19:42

from django.db import migrations


def convert_non_public_status_to_draft(apps, schema_editor):
    '''Convert status choices to new values.'''

    Media = apps.get_model('meta', 'Media')
    Media.objects.filter(is_public=False).update(status='draft')
    Media.objects.filter(is_public=True).update(status='published')


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0223_auto_20240409_1705'),
    ]

    operations = [
        migrations.RunPython(convert_non_public_status_to_draft),
    ]
