# Generated by Django 4.2.11 on 2024-04-30 20:38

from django.db import migrations


def set_general_specialist(apps, schema_editor):
    '''Convert status choices to new values.'''

    Media = apps.get_model('meta', 'Media')
    Person = apps.get_model('meta', 'Person')
    specialist = Person.objects.get(id=68)
    for m in Media.objects.all():
        m.specialists.set([specialist])
        print(m, m.specialists.all())


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0224_auto_20240430_1642'),
    ]

    operations = [
        migrations.RunPython(set_general_specialist),
    ]
