# Generated by Django 4.2.11 on 2024-06-13 23:11

from django.db import migrations


def repopulate_search_vector(apps, schema_editor):
    '''Resave all Media to repopulate the SearchVectorField.'''

    Media = apps.get_model('meta', 'Media')
    for m in Media.objects.all():
        m.save()
        print(m.id)

class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0225_auto_20240430_1738'),
    ]

    operations = [
        migrations.RunPython(repopulate_search_vector),
    ]
