# Generated by Django 4.2.11 on 2024-07-06 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0227_remove_city_name_en_remove_city_name_pt_br_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='country',
            name='name_pt_br',
        ),
    ]
