# Generated by Django 4.2.15 on 2024-08-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0228_remove_country_name_en_remove_country_name_pt_br'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='name',
            field=models.CharField(help_text='Nome chave no estilo bibkey (e.g., Vieira2012-nt).', max_length=100, unique=True, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='slug',
            field=models.SlugField(blank=True, help_text='Slug do nome chave da referência.', max_length=100, verbose_name='slug'),
        ),
    ]
