# Generated by Django 4.2.15 on 2024-08-17 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0229_alter_reference_name_alter_reference_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reference',
            options={'ordering': ['name'], 'verbose_name': 'referência', 'verbose_name_plural': 'referências'},
        ),
    ]
