# Generated by Django 4.2.15 on 2024-08-31 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0230_alter_reference_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxon',
            name='citation',
            field=models.TextField(blank=True, default='', help_text='Citação do táxon.', verbose_name='citação'),
        ),
    ]
