# Generated by Django 4.2.15 on 2024-08-31 22:55

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0231_taxon_citation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxon',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='Táxon pai deste táxon.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='meta.taxon', verbose_name='pai'),
        ),
    ]
