# Generated by Django 4.2.15 on 2024-09-28 14:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meta', '0232_alter_taxon_parent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Curadoria',
            new_name='Curation',
        ),
    ]
