# Generated by Django 4.2.15 on 2024-09-28 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0233_rename_curadoria_curation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curation',
            old_name='taxons',
            new_name='taxa',
        ),
    ]
