# Generated by Django 4.2.15 on 2024-09-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0234_rename_taxons_curation_taxa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curation',
            name='taxa',
            field=models.ManyToManyField(blank=True, help_text='Táxons nesta curadoria.', related_name='curations', to='meta.taxon', verbose_name='táxons'),
        ),
    ]
