# Generated by Django 4.2.15 on 2024-10-06 20:02

from django.db import migrations


def organize_curations(apps, schema_editor):
    '''Set proper names and descriptions to standard curations.'''

    # Get curation model
    Curation = apps.get_model('meta', 'Curation')

    # Set default values for curations
    curation_data = [
        {'id': 1, 'name': 'Cifonauta', 'description': 'Curadoria de todos os táxons presentes no Cifonauta.'},
        {'id': 2, 'name': 'Sem táxons', 'description': 'Curadoria das mídias sem a presença de táxons.'},
        {'id': 3, 'name': 'Presente no WoRMS', 'description': 'Curadoria dos táxons presentes no WoRMS.'},
        {'id': 4, 'name': 'Ausente do WoRMS', 'description': 'Curadoria dos táxons ausentes do WoRMS.'},
        {'id': 5, 'name': 'Echinodermata', 'description': 'Curadoria das mídias com equinodermos.'},
        {'id': 6, 'name': 'Cnidaria', 'description': 'Curadoria das mídias com cnidários.'},
        {'id': 7, 'name': 'Peixes', 'description': 'Curadoria das mídias com peixes.'}
    ]

    # Loop over the data
    for data in curation_data:
        cur, new = Curation.objects.get_or_create(id=data['id'])
        cur.name = data['name']
        cur.description = data['description']
        cur.save()


class Migration(migrations.Migration):

    dependencies = [
        ("meta", "0239_curation_description_curation_slug"),
    ]

    operations = [
        migrations.RunPython(organize_curations)
    ]
