# Generated by Django 5.1.2 on 2024-11-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meta", "0240_auto_20241006_1702"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxon",
            name="on_worms",
            field=models.BooleanField(
                default=False, help_text="Present no WoRMS.", verbose_name="WoRMS"
            ),
        ),
    ]
