# Generated by Django 5.1.2 on 2024-11-02 16:14

from django.db import migrations


def update_on_worms(apps, schema_editor):
    '''Update on_worms boolean field.'''

    # Get curation model
    Taxon = apps.get_model('meta', 'Taxon')

    for t in Taxon.objects.all():
        t.save()


class Migration(migrations.Migration):

    dependencies = [
        ("meta", "0241_taxon_on_worms"),
    ]

    operations = [
        migrations.RunPython(update_on_worms)
    ]
