# Generated by Django 5.1.2 on 2024-11-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0242_auto_20241102_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxon',
            name='on_worms',
            field=models.BooleanField(default=False, help_text='Presente no WoRMS.', verbose_name='WoRMS'),
        ),
    ]
