# Generated by Django 5.1.2 on 2024-11-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meta", "0243_alter_taxon_on_worms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taxon",
            name="is_valid",
            field=models.BooleanField(
                default=False,
                help_text="Status do táxon no WoRMS.",
                verbose_name="válido",
            ),
        ),
        migrations.AlterField(
            model_name="taxon",
            name="on_worms",
            field=models.BooleanField(
                default=False,
                help_text="Indica se o táxon está presente no WoRMS.",
                verbose_name="Presente no WoRMS",
            ),
        ),
    ]
