# Generated by Django 5.1.2 on 2024-11-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meta", "0244_alter_taxon_is_valid_alter_taxon_on_worms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taxon",
            name="on_worms",
            field=models.BooleanField(
                default=False,
                help_text="Indica se o táxon está presente no WoRMS.",
                verbose_name="presente no WoRMS",
            ),
        ),
    ]
