# Generated by Django 5.1.2 on 2024-11-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0246_alter_taxon_is_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='bit_rate',
            field=models.CharField(blank=True, default='', help_text='Bitrate da mídia em bits por segundo (e.g., 30330212).', max_length=20, verbose_name='bitrate da mídia'),
        ),
        migrations.AddField(
            model_name='media',
            name='codec_name',
            field=models.CharField(blank=True, default='', help_text='Nome do codec da mídia (e.g., dvvideo ou mjpeg).', max_length=10, verbose_name='codec da mídia'),
        ),
        migrations.AddField(
            model_name='media',
            name='display_aspect_ratio',
            field=models.CharField(blank=True, default='', help_text='Proporção de aspecto da tela (e.g., 4:3).', max_length=20, verbose_name='Proporção da tela'),
        ),
        migrations.AddField(
            model_name='media',
            name='format_name',
            field=models.CharField(blank=True, default='', help_text='Nome do formato da mídia (e.g., avi ou image2).', max_length=10, verbose_name='formato da mídia'),
        ),
        migrations.AddField(
            model_name='media',
            name='height',
            field=models.PositiveIntegerField(blank=True, help_text='Altura da mídia em pixels (e.g., 720).', null=True, verbose_name='altura da mídia'),
        ),
        migrations.AddField(
            model_name='media',
            name='pix_fmt',
            field=models.CharField(blank=True, default='', help_text='Formato do pixel da mídia (e.g., yuv411p).', max_length=20, verbose_name='formato do pixel'),
        ),
        migrations.AddField(
            model_name='media',
            name='sample_aspect_ratio',
            field=models.CharField(blank=True, default='', help_text='Proporção de aspecto dos píxels (e.g., 8:9).', max_length=20, verbose_name='Proporção do píxel'),
        ),
        migrations.AddField(
            model_name='media',
            name='size',
            field=models.CharField(blank=True, default='', help_text='Tamanho do arquivo original em bytes (e.g., 138519976).', max_length=20, verbose_name='tamanho do arquivo'),
        ),
        migrations.AddField(
            model_name='media',
            name='start_time',
            field=models.CharField(blank=True, default='', help_text='Quando o vídeo stream se inicia (e.g., 0.000000).', max_length=20, verbose_name='início do vídeo'),
        ),
        migrations.AddField(
            model_name='media',
            name='width',
            field=models.PositiveIntegerField(blank=True, help_text='Largura da mídia em pixels (e.g., 720).', null=True, verbose_name='largura da mídia'),
        ),
        migrations.AlterField(
            model_name='media',
            name='duration',
            field=models.CharField(blank=True, default='', help_text='Duração do vídeo em segundos (e.g., 36.536500).', max_length=20, verbose_name='duração do vídeo'),
        ),
    ]
