# Generated by Django 5.1.2 on 2024-11-16 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0247_media_bit_rate_media_codec_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='format_name',
            field=models.CharField(blank=True, default='', help_text='Nome do formato da mídia (e.g., avi ou image2).', max_length=20, verbose_name='formato da mídia'),
        ),
    ]
