# Generated by Django 5.1.2 on 2024-11-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0249_alter_media_format_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='duranew',
            field=models.DurationField(blank=True, help_text='Duração do vídeo em segundos (e.g., 36.536500).', null=True, verbose_name='duração do vídeo'),
        ),
    ]
