# Generated by Django 5.1.2 on 2024-11-17 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0250_media_duranew'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='duration',
        ),
    ]
