# Generated by Django 5.1.2 on 2024-11-17 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0251_remove_media_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='duranew',
            new_name='duration',
        ),
    ]
