# Generated by Django 5.1.2 on 2024-11-17 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0252_rename_duranew_media_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='dimensions',
        ),
    ]
