# Generated by Django 5.1.7 on 2025-03-08 14:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meta", "0253_remove_media_dimensions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="curation",
            name="editors",
            field=models.ManyToManyField(
                blank=True,
                help_text="Editores desta curadoria.",
                related_name="curations_as_editor",
                to=settings.AUTH_USER_MODEL,
                verbose_name="editores",
            ),
        ),
        migrations.AddField(
            model_name="media",
            name="editors",
            field=models.ManyToManyField(
                blank=True,
                help_text="Editores associados a este arquivo.",
                related_name="media_as_editor",
                to="meta.person",
                verbose_name="editores associados",
            ),
        ),
    ]
