# Generated by Django 5.1.7 on 2025-03-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meta", "0254_curation_editors_media_editors"),
    ]

    operations = [
        migrations.AddField(
            model_name="curation",
            name="tmp_curators",
            field=models.ManyToManyField(
                blank=True,
                help_text="Curadores desta curadoria.",
                related_name="tmp_curations_as_curator",
                to="meta.person",
                verbose_name="curadores",
            ),
        ),
        migrations.AddField(
            model_name="curation",
            name="tmp_editors",
            field=models.ManyToManyField(
                blank=True,
                help_text="Editores desta curadoria.",
                related_name="tmp_curations_as_editor",
                to="meta.person",
                verbose_name="editores",
            ),
        ),
        migrations.AddField(
            model_name="curation",
            name="tmp_specialists",
            field=models.ManyToManyField(
                blank=True,
                help_text="Especialistas nesta curadoria.",
                related_name="tmp_curations_as_specialist",
                to="meta.person",
                verbose_name="especialistas",
            ),
        ),
    ]
