# Generated by Django 5.1.7 on 2025-03-09 10:44

from django.db import migrations


def migrate_user_to_person(apps, schema_editor):
    '''Migrate curation data from user to person model.'''

    Curation = apps.get_model('meta', 'Curation')
    Person = apps.get_model('meta', 'Person')
    
    for curation in Curation.objects.all():
        # Migrate curators data
        curator_users = curation.curators.all()
        curator_persons = Person.objects.filter(user_cifonauta__in=curator_users)
        curation.tmp_curators.add(*curator_persons)
        # Migrate specialists data
        specialist_users = curation.specialists.all()
        specialist_persons = Person.objects.filter(user_cifonauta__in=specialist_users)
        curation.tmp_specialists.add(*specialist_persons)
        # Migrate editors data
        editor_users = curation.editors.all()
        editor_persons = Person.objects.filter(user_cifonauta__in=editor_users)
        curation.tmp_editors.add(*editor_persons)
        # Save just in case
        curation.save()


class Migration(migrations.Migration):

    dependencies = [
        ("meta", "0255_curation_tmp_curators_curation_tmp_editors_and_more"),
    ]

    operations = [
            migrations.RunPython(migrate_user_to_person)
            ]
