# Generated by Django 5.1.7 on 2025-03-09 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meta", "0256_auto_20250309_0744"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="curation",
            name="curators",
        ),
        migrations.RemoveField(
            model_name="curation",
            name="editors",
        ),
        migrations.RemoveField(
            model_name="curation",
            name="specialists",
        ),
    ]
