# Generated by Django 5.1.7 on 2025-03-09 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meta", "0257_remove_curation_curators_remove_curation_editors_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="curation",
            old_name="tmp_curators",
            new_name="curators",
        ),
        migrations.RenameField(
            model_name="curation",
            old_name="tmp_editors",
            new_name="editors",
        ),
        migrations.RenameField(
            model_name="curation",
            old_name="tmp_specialists",
            new_name="specialists",
        ),
    ]
