# Generated by Django 5.1.7 on 2025-03-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meta", "0258_rename_tmp_curators_curation_curators_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curation",
            name="curators",
            field=models.ManyToManyField(
                blank=True,
                help_text="Curadores desta curadoria.",
                related_name="curations_as_curator",
                to="meta.person",
                verbose_name="curadores",
            ),
        ),
        migrations.AlterField(
            model_name="curation",
            name="editors",
            field=models.ManyToManyField(
                blank=True,
                help_text="Editores desta curadoria.",
                related_name="curations_as_editor",
                to="meta.person",
                verbose_name="editores",
            ),
        ),
        migrations.AlterField(
            model_name="curation",
            name="specialists",
            field=models.ManyToManyField(
                blank=True,
                help_text="Especialistas nesta curadoria.",
                related_name="curations_as_specialist",
                to="meta.person",
                verbose_name="especialistas",
            ),
        ),
    ]
