# Generated by Django 5.1.7 on 2025-03-11 19:30

from django.db import migrations


def migrate_specialist_to_editor(apps, schema_editor):
    '''Migrate curation data from specialist to editor.'''

    Curation = apps.get_model('meta', 'Curation')
    
    for curation in Curation.objects.all():
        specialists = curation.specialists.all()
        curation.editors.add(*specialists)
        curation.save()


class Migration(migrations.Migration):

    dependencies = [
        ("meta", "0259_alter_curation_curators_alter_curation_editors_and_more"),
    ]

    operations = [
            migrations.RunPython(migrate_specialist_to_editor)
            ]

