# Generated by Django 5.1.7 on 2025-03-11 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meta", "0260_auto_20250311_1630"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="curation",
            name="specialists",
        ),
    ]
