# Generated by Django 5.1.7 on 2025-03-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meta", "0261_remove_curation_specialists"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taxon",
            name="name",
            field=models.CharField(
                help_text="Nome do táxon.", max_length=256, verbose_name="nome"
            ),
        ),
    ]
