# Generated by Django 5.1.7 on 2025-03-18 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meta", "0262_alter_taxon_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taxon",
            name="aphia",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="AphiaID, o identificador do táxon no WoRMS.",
                null=True,
                unique=True,
            ),
        ),
    ]
