# Generated by Django 5.1.7 on 2025-03-18 20:51

from django.db import migrations


def resave_taxon_slug(apps, schema_editor):
    '''Resave taxa to ensure unique slugs.'''

    Taxon = apps.get_model('meta', 'Taxon')
    
    for taxon in Taxon.objects.all():
        taxon.save()


class Migration(migrations.Migration):

    dependencies = [
        ("meta", "0263_alter_taxon_aphia"),
    ]

    operations = [
            migrations.RunPython(resave_taxon_slug)
            ]
