# Generated by Django 5.1.7 on 2025-03-18 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meta", "0264_auto_20250318_1751"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taxon",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Slug do nome do táxon.",
                max_length=256,
                unique=True,
                verbose_name="slug",
            ),
        ),
    ]
