# Generated by Django 4.2.1 on 2023-06-29 22:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercifonauta',
            name='idlattes',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.MaxValueValidator(9999999999999999), django.core.validators.MaxLengthValidator(16)], verbose_name='IDLattes'),
        ),
    ]
