# Generated by Django 4.2.1 on 2023-06-29 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercifonauta',
            name='is_staff',
        ),
    ]
