# Generated by Django 4.2.1 on 2023-06-29 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_usercifonauta_idlattes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercifonauta',
            name='idlattes',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='IDLattes'),
        ),
        migrations.AlterField(
            model_name='usercifonauta',
            name='orcid',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Orcid'),
        ),
    ]
