# Generated by Django 4.2.1 on 2023-06-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_usercifonauta_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercifonauta',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
