# Generated by Django 4.2.1 on 2023-07-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_usercifonauta_idlattes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercifonauta',
            name='first_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Primeiro Nome'),
        ),
        migrations.AlterField(
            model_name='usercifonauta',
            name='idlattes',
            field=models.CharField(max_length=16, null=True, verbose_name='IDLattes'),
        ),
        migrations.AlterField(
            model_name='usercifonauta',
            name='last_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Último Nome'),
        ),
        migrations.AlterField(
            model_name='usercifonauta',
            name='orcid',
            field=models.CharField(max_length=16, null=True, verbose_name='Orcid'),
        ),
    ]
