# Generated by Django 4.2.1 on 2023-07-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0069_media_author_media_curadoria_media_file_media_status'),
        ('user', '0004_alter_usercifonauta_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercifonauta',
            name='curadoria',
            field=models.ManyToManyField(blank=True, to='meta.curadoria'),
        ),
    ]
