# Generated by Django 4.2.1 on 2023-07-22 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0068_remove_media_country_categoria_media_categoria'),
        ('user', '0004_alter_usercifonauta_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercifonauta',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meta.categoria'),
        ),
    ]
