# Generated by Django 4.2.1 on 2023-08-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_usercifonauta_curadoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercifonauta',
            name='is_author',
            field=models.BooleanField(default=False, help_text='Informa se o usuário é autor.', verbose_name='Autor'),
        ),
    ]
