# Generated by Django 4.2.1 on 2023-08-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0078_alter_curadoria_curators_alter_curadoria_specialists'),
        ('user', '0006_usercifonauta_is_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercifonauta',
            name='curator_of',
            field=models.ManyToManyField(blank=True, related_name='curator_of', to='meta.curadoria'),
        ),
        migrations.AddField(
            model_name='usercifonauta',
            name='specialist_of',
            field=models.ManyToManyField(blank=True, related_name='specialist_of', to='meta.curadoria'),
        ),
    ]
