# Generated by Django 4.2.1 on 2023-08-08 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_usercifonauta_curator_of_usercifonauta_specialist_of'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercifonauta',
            name='curadoria',
        ),
    ]
