# Generated by Django 4.2.1 on 2023-08-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0078_alter_curadoria_curators_alter_curadoria_specialists'),
        ('user', '0008_remove_usercifonauta_curadoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercifonauta',
            name='curator_of',
            field=models.ManyToManyField(blank=True, help_text='Mostra de quais curadorias o usuário é curador.', related_name='curator_of', to='meta.curadoria', verbose_name='curador de'),
        ),
        migrations.AlterField(
            model_name='usercifonauta',
            name='specialist_of',
            field=models.ManyToManyField(blank=True, help_text='Mostra de quais curadorias o usuário é especialista.', related_name='specialist_of', to='meta.curadoria', verbose_name='especialista de'),
        ),
    ]
