# Generated by Django 4.2.1 on 2023-08-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0083_alter_media_has_taxons'),
        ('user', '0008_remove_usercifonauta_curadoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, null=True, verbose_name='Primeiro Nome')),
                ('last_name', models.CharField(max_length=50, null=True, verbose_name='Último Nome')),
                ('orcid', models.CharField(max_length=16, null=True, verbose_name='Orcid')),
            ],
        ),
        migrations.AlterField(
            model_name='usercifonauta',
            name='curator_of',
            field=models.ManyToManyField(blank=True, help_text='Mostra de quais curadorias o usuário é curador.', related_name='curator_of', to='meta.curadoria', verbose_name='curador de'),
        ),
        migrations.AlterField(
            model_name='usercifonauta',
            name='specialist_of',
            field=models.ManyToManyField(blank=True, help_text='Mostra de quais curadorias o usuário é especialista.', related_name='specialist_of', to='meta.curadoria', verbose_name='especialista de'),
        ),
    ]
