# Generated by Django 4.2.1 on 2023-08-15 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_usercifonauta_curator_of_and_more'),
        ('user', '0010_delete_userpreregistration'),
    ]

    operations = [
    ]
