# Generated by Django 4.2.1 on 2023-09-05 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_usercifonauta_idlattes'),
        ('user', '0011_merge_20230815_1631'),
    ]

    operations = [
    ]
