# Generated by Django 4.2.1 on 2023-10-15 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_merge_20230905_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercifonauta',
            name='curator_of',
        ),
        migrations.RemoveField(
            model_name='usercifonauta',
            name='specialist_of',
        ),
    ]
